## NeoForge / Environment Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1.228,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT

## Mod Properties
mod_id=mi_sound_addon
mod_name=MI Sound Addon
mod_license=MIT
mod_version=1.4.0
mod_group_id=dev.thestaticvoid
mod_authors=staitc
mod_description=Sound addon for Modern Industrialization

## Dependency Versions
ei_version=1.15.45
ei_version_range=[1.15.25-1.21.1,)
io_version=1089065:8409629
io_version_range=[1.12.0+1.21.1,)
kff_version=5.12.0
kff_version_range=[5.12.0,)
kubejs_version=2101.7.2-build.348
kubejs_version_range=[2101.7.2-build.348,)
mi_version=2.5.5
mi_version_range=[2.5,2.6)
yai_version=1358516:8482106
yai_version_range=[1.6.1-1.12.1,)